version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - my-network

  # 추가
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "grafana"
    ports:
      - "3000:3000"
    volumes:
      - grafana-volume:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - my-network

volumes:
  prometheus_data:
  grafana-volume:

networks:
  my-network:
    driver: bridge