scrape_configs:
  - job_name: 'eureka'
    metrics_path: '/monitoring/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8299']

  - job_name: 'gate-way'
    metrics_path: '/monitoring/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8888' ]


